-- MySQL Script generated by MySQL Workbench
-- Mon Jun 23 15:59:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taskdb1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskdb1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskdb1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `taskdb1` ;

-- -----------------------------------------------------
-- Table `taskdb1`.`authors_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskdb1`.`authors_table` (
  `author_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskdb1`.`books_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskdb1`.`books_table` (
  `book_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `author_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_author_id_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `taskdb1`.`authors_table` (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskdb1`.`student_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskdb1`.`student_table` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `course` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskdb1`.`issue_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskdb1`.`issue_table` (
  `issue_id` INT NOT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `student_id` INT NULL DEFAULT NULL,
  `issue_date` DATE NULL DEFAULT NULL,
  `return_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`issue_id`),
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `taskdb1`.`books_table` (`book_id`),
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `taskdb1`.`student_table` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
